export type PaletteColor = {
  id: string
  name: string
  hex: string
}

export const beadPalette: PaletteColor[] = [
  { id: 'white', name: '白色', hex: '#f7f7f2' },
  { id: 'ivory', name: '米白1', hex: '#f1ead8' },
  { id: 'sand', name: '米色1', hex: '#dcc7a1' },
  { id: 'beige', name: '米棕1', hex: '#b99f7a' },
  { id: 'stone', name: '浅灰1', hex: '#d5d6d2' },
  { id: 'silver', name: '中灰1', hex: '#acafb4' },
  { id: 'slate', name: '深灰1', hex: '#6a7078' },
  { id: 'charcoal', name: '炭黑1', hex: '#23262c' },
  { id: 'cream', name: '浅黄1', hex: '#fbefb8' },
  { id: 'butter', name: '浅黄2', hex: '#f6e17d' },
  { id: 'sun', name: '黄色1', hex: '#f4cd2f' },
  { id: 'amber', name: '黄色5', hex: '#eab11f' },
  { id: 'orange', name: '橙色2', hex: '#ef8f23' },
  { id: 'tangerine', name: '橙色5', hex: '#e36b11' },
  { id: 'coral', name: '橙红2', hex: '#ee6249' },
  { id: 'salmon', name: '橙红5', hex: '#d74c3b' },
  { id: 'scarlet', name: '正红1', hex: '#d8342a' },
  { id: 'ruby', name: '亮红2', hex: '#b81f33' },
  { id: 'wine', name: '深红1', hex: '#7d1722' },
  { id: 'rose', name: '粉红2', hex: '#f4a5b7' },
  { id: 'pink', name: '浅粉3', hex: '#f8c7d6' },
  { id: 'peach', name: '粉橙2', hex: '#f8c1a1' },
  { id: 'mauve', name: '灰粉3', hex: '#d59ca5' },
  { id: 'plum', name: '紫红2', hex: '#a54f78' },
  { id: 'lavender', name: '浅紫2', hex: '#cdb6ee' },
  { id: 'lilac', name: '浅紫6', hex: '#ae8ddb' },
  { id: 'violet', name: '紫罗兰2', hex: '#7c57b8' },
  { id: 'grape', name: '深紫2', hex: '#5f378d' },
  { id: 'navy', name: '深蓝1', hex: '#214f9b' },
  { id: 'deep-blue', name: '深蓝4', hex: '#17376e' },
  { id: 'sky', name: '天蓝2', hex: '#89caf3' },
  { id: 'ice', name: '浅蓝2', hex: '#bfe7fb' },
  { id: 'cyan', name: '青蓝4', hex: '#4ea5dd' },
  { id: 'ocean', name: '青蓝7', hex: '#2d7ab4' },
  { id: 'mint', name: '薄荷绿1', hex: '#c6f0d2' },
  { id: 'aqua', name: '浅青1', hex: '#8fe6e3' },
  { id: 'turquoise', name: '蓝绿3', hex: '#33bcb1' },
  { id: 'teal', name: '深蓝绿1', hex: '#17887c' },
  { id: 'lime', name: '青柠绿1', hex: '#d3ef76' },
  { id: 'leaf', name: '亮绿2', hex: '#87c83d' },
  { id: 'green', name: '翠绿2', hex: '#4ea24d' },
  { id: 'forest', name: '森林绿2', hex: '#2f6d3b' },
  { id: 'olive', name: '橄榄绿2', hex: '#6e7b3c' },
  { id: 'khaki', name: '黄绿4', hex: '#9aa24e' },
  { id: 'brown', name: '浅棕2', hex: '#bb8a5a' },
  { id: 'caramel', name: '棕橙1', hex: '#a7673f' },
  { id: 'cocoa', name: '棕褐2', hex: '#7d4c2e' },
  { id: 'chocolate', name: '深棕1', hex: '#55301c' },
  { id: 'umber', name: '深棕黑', hex: '#34241a' },
  { id: 'blue-grey', name: '蓝灰2', hex: '#7e8ea0' },
  { id: 'sage', name: '灰绿1', hex: '#8f9a7c' },
  { id: 'dusty-rose', name: '灰粉6', hex: '#bf8d90' },
  { id: 'purple-grey', name: '紫灰1', hex: '#968ca9' },
]
